# Generated by Django 5.0.7 on 2024-08-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(choices=[(3, '3ème Post Fondemental'), (9, '9è Fondemental')], max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
