# Generated by Django 5.0.7 on 2024-08-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactmessage',
            table='api_contactmessage',
        ),
        migrations.AlterModelTable(
            name='sendemail',
            table='api_sendemail',
        ),
    ]
