# Generated by Django 5.0.7 on 2024-08-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_course_grade_delete_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(choices=[('3', '3ème Post Fondemental'), ('9', '9è Fondemental')], max_length=40, null=True),
        ),
    ]
