# Generated by Django 5.0.7 on 2024-08-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_contactmessage_table_alter_sendemail_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactmessage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sendemail',
            table=None,
        ),
    ]
