# Generated by Django 5.0.6 on 2024-07-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_epreuve_link_epreuve_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exetat',
            name='link',
            field=models.FileField(default='', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='exetat',
            name='type',
            field=models.CharField(choices=[('Q', 'Questionnaire'), ('A', 'Answers')], default='Q', max_length=1),
        ),
    ]
